# Generated by Django 5.1.6 on 2025-02-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('match_experience', models.CharField(choices=[('10', '10 Matches'), ('20', '20 Matches'), ('30', '30 Matches'), ('40+', '40+ Matches')], max_length=10)),
                ('player_role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-Rounder', 'All-Rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], max_length=20)),
                ('player_image', models.ImageField(upload_to='player_images/')),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('address', models.TextField(default='Address')),
                ('phone_no', models.IntegerField()),
                ('image', models.ImageField(upload_to='player_images/')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='academy.playerlist')),
            ],
        ),
    ]
