# Generated by Django 5.1.6 on 2025-02-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_player_player_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerrole',
            name='address',
        ),
        migrations.RemoveField(
            model_name='playerrole',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='playerrole',
            name='match_experience',
        ),
        migrations.RemoveField(
            model_name='playerrole',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='playerrole',
            name='player_image',
        ),
        migrations.RemoveField(
            model_name='playerrole',
            name='player_name',
        ),
    ]
