# Generated by Django 5.1.6 on 2025-02-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_remove_playerrole_address_remove_playerrole_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(blank=True, upload_to='player_images/'),
        ),
    ]
