# Generated by Django 5.1.6 on 2025-02-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_feedback_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
